// Comprehensive bilingual text pairs used by navbar language switch.
// Generated from explicit bilingual bindings, service dictionaries, and deep module audit.
export const GLOBAL_EN_BN: Record<string, string> = {
  "-- Select --": "-- নির্বাচন করুন --",
  "-- Select Day --": "-- দিন নির্বাচন করুন --",
  "-- Select Type --": "-- ধরন নির্বাচন করুন --",
  "-- Select Ward --": "-- ওয়ার্ড নির্বাচন করুন --",
  "Access Denied": "অ্যাক্সেস নিষিদ্ধ",
  "Account No.": "অ্যাকাউন্ট নং",
  "Account Number": "অ্যাকাউন্ট নম্বর",
  "Action": "অ্যাকশন",
  "Actions": "অ্যাকশন",
  "Active": "সক্রিয়",
  "Active Election": "চলমান নির্বাচন",
  "Active Notices": "সক্রিয় নোটিশ",
  "Add": "যোগ করুন",
  "Add New Stock": "নতুন স্টক যোগ করুন",
  "Address": "ঠিকানা",
  "Address is required": "ঠিকানা আবশ্যক",
  "Admin Final Approval": "অ্যাডমিন চূড়ান্ত অনুমোদন",
  "Admin Officer": "অ্যাডমিন কর্মকর্তা",
  "Administration": "প্রশাসন",
  "Agrani Bank": "অগ্রণী ব্যাংক",
  "Agricultural Bank": "কৃষি ব্যাংক",
  "Agricultural Information": "কৃষি তথ্য",
  "All": "সকল",
  "All Apply Data": "সব আবেদন তথ্য",
  "All Citizens": "সকল নাগরিক",
  "All Complaints": "সব অভিযোগ",
  "All Days": "সকল দিন",
  "All Months": "সকল মাস",
  "All Roles": "সকল ভূমিকা",
  "All Services Active": "সকল সেবা সক্রিয়",
  "All Status": "সকল অবস্থা",
  "All Statuses": "সকল স্ট্যাটাস",
  "All Types": "সকল ধরন",
  "All Wards": "সকল ওয়ার্ড",
  "Already have an account?": "ইতিমধ্যে অ্যাকাউন্ট আছে?",
  "Amount": "পরিমাণ",
  "Amount (BDT)": "পরিমাণ (টাকা)",
  "Analytics Report": "বিশ্লেষণ প্রতিবেদন",
  "App. Status": "আবেদনের অবস্থা",
  "Applicant": "আবেদনকারী",
  "Applicant & Holding Information": "আবেদনকারী ও হোল্ডিং তথ্য",
  "Applicant Information": "আবেদনকারীর তথ্য",
  "Applicant Name": "আবেদনকারীর নাম",
  "Applicant Photo": "আবেদনকারীর ছবি",
  "Applicant's Name": "আবেদনকারীর নাম",
  "Application Details": "আবেদনের তথ্য",
  "Application Form": "আবেদন ফরম",
  "Application ID": "আবেদন আইডি",
  "Application Status": "আবেদনের অবস্থা",
  "Application Status Verification": "আবেদনের অবস্থা যাচাই",
  "Application submission and approval/rejection notifications": "আবেদন জমা ও অনুমোদন/প্রত্যাখ্যানের বিজ্ঞপ্তি",
  "Application Submitted": "আবেদন জমা",
  "application(s)": "টি আবেদন",
  "Apply": "আবেদন",
  "Apply for License": "লাইসেন্সের আবেদন",
  "Approve": "অনুমোদন",
  "Approve Now": "অনুমোদন করুন",
  "Approved": "অনুমোদিত",
  "Approved cards by ward": "ওয়ার্ড-ভিত্তিক অনুমোদিত কার্ড সংখ্যা",
  "Approved Farmer": "অনুমোদিত কৃষক",
  "Area": "এলাকা",
  "Area / Location": "এলাকা / অবস্থান",
  "Area and Dealer Information": "এলাকা ও ডিলারের তথ্য",
  "Area Information and Family": "এলাকার তথ্য ও পরিবার",
  "Area is required": "এলাকা আবশ্যক",
  "Area Name": "এলাকার নাম",
  "Area Name / Address": "এলাকার নাম / ঠিকানা",
  "Attendance Management": "উপস্থিতি ব্যবস্থাপনা",
  "Audit Logs": "অডিট লগ",
  "Auditor / Accountant": "হিসাবরক্ষক",
  "Authority Remarks": "কর্তৃপক্ষের মন্তব্য",
  "Autism": "অটিজম",
  "Available Stock": "বর্তমান স্টক",
  "Awarded To": "পুরষ্কৃত",
  "Back": "পিছনে",
  "Bank Account No.": "ব্যাংক অ্যাকাউন্ট নং",
  "Bank Name": "ব্যাংকের নাম",
  "Batch": "ব্যাচ",
  "Batch Label": "ব্যাচ লেবেল",
  "Batch No.": "ব্যাচ নং",
  "Beneficiary": "উপকারভোগী",
  "Beneficiary Name": "সুবিধাভোগীর নাম",
  "Bid Amount": "বিডের পরিমাণ",
  "Bid Closed": "বিড বন্ধ",
  "Birth / Death": "জন্ম / মৃত্যু",
  "Birth / Death Certificate": "জন্ম / মৃত্যু সনদ",
  "Birth Certificate": "জন্ম সনদ",
  "Birth Registration No.": "জন্ম নিবন্ধন নং",
  "bKash": "বিকাশ",
  "Blacklist Reason": "ব্ল্যাকলিস্টের কারণ",
  "Blacklist the Vendor": "বিক্রেতাকে ব্ল্যাকলিস্ট করুন",
  "Blacklisted": "ব্ল্যাকলিস্টেড",
  "Blood Group": "রক্তের গ্রুপ",
  "Both": "উভয়",
  "Brother": "ভাই",
  "Buddhism": "বৌদ্ধ",
  "Building Construction Permission Application Form": "ভবন নির্মাণ অনুমতি আবেদন ফর্ম",
  "Building Type": "ভবনের ধরন",
  "Bulk Waste": "বাল্ক বর্জ্য",
  "Business Address": "ব্যবসার ঠিকানা",
  "Business Name": "ব্যবসার নাম",
  "Business Type": "ব্যবসার ধরন",
  "By Cycle": "চক্র ভিত্তিক",
  "Cancel": "বাতিল",
  "Cancelled": "বাতিল",
  "Candidate Application": "প্রার্থী আবেদন",
  "Candidate Approval": "প্রার্থী অনুমোদন",
  "Candidate List": "প্রার্থী তালিকা",
  "Candidate Name": "প্রার্থীর নাম",
  "Card Holder": "কার্ড ধারক",
  "Card holder full information": "কার্ডধারীর সম্পূর্ণ তথ্য প্রদান করুন",
  "Card Holder Name": "কার্ডধারীর নাম",
  "Card Lookup": "কার্ড অনুসন্ধান",
  "Card No": "কার্ড নম্বর",
  "Card No.": "কার্ড নং",
  "Card Number": "কার্ড নম্বর",
  "Card Type and Personal Information": "কার্ডের ধরন ও ব্যক্তিগত তথ্য",
  "Cash": "নগদ",
  "Cash (BDT)": "নগদ (টাকা)",
  "Cash (৳)": "নগদ (৳)",
  "Cast Vote": "ভোট প্রদান",
  "Category": "বিভাগ",
  "Change Email": "ইমেইল পরিবর্তন",
  "Change Password": "পাসওয়ার্ড পরিবর্তন",
  "Changing status...": "স্ট্যাটাস পরিবর্তন...",
  "Check Application Status": "আবেদনের অবস্থা দেখুন",
  "Check My Status": "আবেদনের অবস্থা",
  "Check Status": "অবস্থা দেখুন",
  "Child": "শিশুর ব্যক্তিগত তথ্য",
  "Child EPI Registration — Expanded Programme on Immunization (EPI)": "শিশু ইপিআই নিবন্ধন ফরম",
  "Child's Name": "শিশুর নাম",
  "Child's Personal Information": "শিশুর ব্যক্তিগত তথ্য",
  "Christianity": "খ্রিস্টান",
  "Citizen / User": "নাগরিক",
  "Citizen Cert.": "নাগরিক সনদ",
  "Citizen Certificate": "নাগরিক সনদ",
  "Citizen Feedback": "নাগরিক মতামত",
  "Citizen Feedback &amp; Complaint — Communication Division": "নাগরিক ফিডব্যাক ফরম",
  "Citizen Feedback Management — Communication Division": "নাগরিক ফিডব্যাক ব্যবস্থাপনা",
  "Citizen Information": "নাগরিক তথ্য",
  "Citizen Report": "নাগরিক প্রতিবেদন",
  "Citizen Service": "নাগরিক সেবা",
  "Clear Filters": "ফিল্টার মুছুন",
  "Close": "বন্ধ করুন",
  "Closed": "বন্ধ",
  "Collect": "সংগ্রহ করুন",
  "Collected Today": "আজকে সংগ্রহ",
  "Collection Day": "সংগ্রহের দিন",
  "Collection Report": "সংগ্রহ প্রতিবেদন",
  "Collection Time": "সংগ্রহের সময়",
  "Comments": "মন্তব্য",
  "Communication": "যোগাযোগ",
  "Complaint": "অভিযোগ",
  "Complaint Details": "অভিযোগের বিবরণ",
  "Complaint Resolution — Citizen Complaint Management System": "অভিযোগ সমাধান ব্যবস্থাপনা",
  "Complaint Status": "অভিযোগের অবস্থা",
  "Complaint Tracking — Citizen Complaint Management System": "অভিযোগ ট্র্যাকিং সিস্টেম",
  "Completed": "সম্পন্ন",
  "Completed Election": "সম্পন্ন নির্বাচন",
  "Confirm": "নিশ্চিত করুন",
  "Confirm Password": "পাসওয়ার্ড নিশ্চিত",
  "Congratulations!": "অভিনন্দন!",
  "Connection Type": "সংযোগের ধরন",
  "Construction": "নির্মাণ",
  "Construction Permission": "নির্মাণ অনুমতি",
  "Construction Waste": "নির্মাণ বর্জ্য",
  "Contact": "যোগাযোগ",
  "Contact Number": "যোগাযোগ নম্বর",
  "Create": "তৈরি করুন",
  "Create and monitor monthly rice, wheat and cash assistance stock": "মাসিক চাল, গম ও নগদ সহায়তার স্টক তৈরি ও পর্যবেক্ষণ করুন",
  "Current Password": "বর্তমান পাসওয়ার্ড",
  "Current Status:": "বর্তমান অবস্থা:",
  "Cycle": "চক্র",
  "Cycle (Month)": "চক্র (মাস)",
  "Cycle and card-based distribution records and session list": "চক্র ও কার্ড ভিত্তিক বিতরণ রেকর্ড ও সেশন তালিকা",
  "Dashboard": "ড্যাশবোর্ড",
  "Data is loading...": "তথ্য লোড হচ্ছে...",
  "Date": "তারিখ",
  "Date of Birth": "জন্ম তারিখ",
  "Date of Death": "মৃত্যু তারিখ",
  "Daughter": "কন্যা",
  "Day": "দিন",
  "Day selection is required": "দিন নির্বাচন আবশ্যক",
  "Deadline": "সময়সীমা",
  "Dealer": "ডিলার",
  "Dealer Name": "ডিলারের নাম",
  "Death Certificate": "মৃত্যু সনদ",
  "Deceased": "মৃত ব্যক্তির এনআইডি",
  "Deceased Person": "মৃত ব্যক্তির তথ্য",
  "Deceased Person's Information": "মৃত ব্যক্তির তথ্য",
  "Deceased's NID Card": "মৃত ব্যক্তির এনআইডি",
  "Delete": "মুছুন",
  "Department Assignment": "বিভাগ নিয়োগ",
  "Department of Immigration &amp; Passports": "পাসপোর্ট আবেদন ফরম",
  "Department Officer": "বিভাগীয় কর্মকর্তা",
  "Department Verification": "বিভাগীয় যাচাই",
  "Description": "বিবরণ",
  "Details": "বিবরণ",
  "Development Projects": "উন্নয়ন প্রকল্প",
  "Digital Service Portal": "ডিজিটাল সেবা পোর্টাল",
  "Distribution History": "বিতরণ ইতিহাস",
  "Distribution List": "বিতরণ তালিকা",
  "Distribution:": "বিতরণ:",
  "Distributions in this session": "এই সেশনের বিতরণ",
  "Distributor": "বিতরণকারী",
  "Distributor Name": "বিতরণকারীর নাম",
  "District": "জেলা",
  "Divorced": "তালাকপ্রাপ্ত",
  "Documents": "কাগজপত্র",
  "Don": "অ্যাকাউন্ট নেই?",
  "Don't have an account?": "অ্যাকাউন্ট নেই?",
  "Download": "ডাউনলোড",
  "Download Card (PDF)": "কার্ড ডাউনলোড করুন (পিডিএফ)",
  "Download failed": "ডাউনলোড ব্যর্থ হয়েছে",
  "Download PDF": "পিডিএফ ডাউনলোড",
  "Download permission was denied. Please sign in again and retry.": "ডাউনলোড অনুমতি পাওয়া যায়নি। অনুগ্রহ করে আবার লগইন করে চেষ্টা করুন।",
  "Drain Type": "ড্রেনের ধরন",
  "Drainage": "ড্রেনেজ",
  "Drainage Infrastructure Development Request Form": "ড্রেনেজ অবকাঠামো উন্নয়ন আবেদন ফর্ম",
  "Due Amount": "বকেয়া পরিমাণ",
  "Due Date": "শেষ তারিখ",
  "E-Governance": "ই-গভর্ন্যান্স",
  "E-Tender": "ই-টেন্ডার",
  "E-Tender Admin": "ই-টেন্ডার অ্যাডমিন",
  "E-Tender Bid": "ই-টেন্ডার বিড",
  "E-Tender Bid Submission Form": "ই-টেন্ডার বিড জমা ফর্ম",
  "E-Tender Notices": "ই-টেন্ডার বিজ্ঞপ্তি",
  "E-Tender Portal": "ই-টেন্ডার পোর্টাল",
  "E-Voting": "ই-ভোটিং",
  "E-Waste": "ই-বর্জ্য",
  "Edit": "সম্পাদনা",
  "Election": "নির্বাচন",
  "Election Declaration": "নির্বাচন ঘোষণা",
  "Election Name": "নির্বাচনের নাম",
  "Election Nomination Form — E-Voting System": "প্রার্থী মনোনয়ন ফরম",
  "Election Result": "নির্বাচন ফলাফল",
  "Email": "ইমেইল",
  "Email Address": "ইমেইল ঠিকানা",
  "Emergency Contact Name": "জরুরি যোগাযোগের নাম",
  "Emergency Phone": "জরুরি ফোন",
  "Employee": "কর্মচারী",
  "Employee Registration": "কর্মচারী নিবন্ধন",
  "en-GB": "bn-BD",
  "End": "শেষ",
  "End Date": "শেষের তারিখ",
  "Enter applicant personal details and holding identification": "আবেদনকারীর ব্যক্তিগত তথ্য ও হোল্ডিং পরিচিতি দিন",
  "Enter card number": "কার্ড নম্বর লিখুন",
  "Enter Mobile Number": "মোবাইল নম্বর দিন",
  "Enter mobile number": "মোবাইল নম্বর দিন",
  "Enter OTP": "OTP দিন",
  "Enter your mobile number": "আপনার মোবাইল নম্বর দিন",
  "Enter your registered email. We will send a verification code.": "আপনার নিবন্ধিত ইমেইল দিন। আমরা একটি যাচাইকরণ কোড পাঠাব।",
  "EPI Admin": "ইপিআই অ্যাডমিন",
  "EPI Registration": "ইপিআই নিবন্ধন",
  "Estimated Cost": "আনুমানিক খরচ",
  "Existing Holding Number": "বর্তমান হোল্ডিং নম্বর",
  "Expiry Date": "মেয়াদ শেষের তারিখ",
  "Failed": "ব্যর্থ",
  "Family Card": "পারিবারিক কার্ড",
  "Family Card (TCB) Apply": "পারিবারিক কার্ড (টিসিবি) আবেদন",
  "Family Card Admin": "পারিবারিক কার্ড অ্যাডমিন",
  "Family Card Application Form — Trading Corporation of Bangladesh": "পরিবার কার্ড আবেদন ফরম (TCB)",
  "Family Card Status": "পারিবারিক কার্ডের অবস্থা",
  "Family Cert.": "পারিবারিক সনদ",
  "Family Certificate": "পারিবারিক সনদ",
  "Family Information": "পারিবারিক তথ্য",
  "Family Members": "পরিবারের সদস্য",
  "Farm Distribution": "কৃষি বিতরণ",
  "Farmer": "কৃষক",
  "Farmer Card": "কৃষক কার্ড",
  "Farmer Card Admin": "কৃষক কার্ড অ্যাডমিন",
  "Farmer Card Application Form — Department of Agricultural Extension": "কৃষক কার্ড আবেদন ফরম",
  "Farmer Card Apply": "কৃষক কার্ড আবেদন",
  "Farmer Card Status": "কৃষক কার্ডের অবস্থা",
  "Farmer Distribution": "কৃষক বিতরণ",
  "Farmer Fertilizer/Seed Distribution": "কৃষক সার/বীজ বিতরণ",
  "Farmer Name": "কৃষকের নাম",
  "Farmer Stock & Distribution Management": "কৃষক স্টক ও বিতরণ ব্যবস্থাপনা",
  "Farmers": "কৃষক",
  "Father": "পিতা",
  "Father's Date of Birth": "পিতার জন্ম তারিখ",
  "Father's Email": "পিতার ইমেইল",
  "Father's Full Name": "পিতার পূর্ণ নাম",
  "Father's full name": "পিতার পূর্ণ নাম",
  "Father's Information": "পিতার তথ্য",
  "Father's Mobile": "পিতার মোবাইল",
  "Father's Name": "পিতার নাম",
  "Father's NID File": "পিতার এনআইডি ফাইল",
  "Father's NID Number": "পিতার এনআইডি নম্বর",
  "Feedback Admin": "মতামত অ্যাডমিন",
  "Female": "মহিলা",
  "Fertilizer/Seed Scan": "সার/বীজ স্ক্যান",
  "Fields marked * are mandatory": "* চিহ্নিত ঘরগুলো আবশ্যক",
  "Fill in the information below to start distribution": "বিতরণ শুরু করতে নিচের তথ্য পূরণ করুন",
  "Fill in the waste collection date and area information": "বর্জ্য সংগ্রহের তারিখ ও এলাকার তথ্য পূরণ করুন",
  "Fill Level": "ভর্তির মাত্রা",
  "Filter": "ফিল্টার",
  "First Approved": "প্রথম ধাপ অনুমোদিত",
  "Forgot Password?": "পাসওয়ার্ড ভুলে গেছেন?",
  "Full (≥80%)": "ভর্তি (≥80%)",
  "Full Address": "সম্পূর্ণ ঠিকানা",
  "Full Name": "সম্পূর্ণ নাম",
  "Full name": "পূর্ণ নাম",
  "Full Name (Bangla)": "পূর্ণ নাম (বাংলায়)",
  "Full Name (English)": "পূর্ণ নাম (ইংরেজিতে)",
  "G2P Transfer": "জি২পি ট্রান্সফার",
  "Garbage Collection Schedule": "বর্জ্য সংগ্রহের সময়সূচি",
  "Garbage Schedule": "বর্জ্য সময়সূচি",
  "Gender": "লিঙ্গ",
  "General Settings": "সাধারণ সেটিংস",
  "Get notifications": "বিজ্ঞপ্তি পেতে",
  "GIS / Map": "জিআইএস / মানচিত্র",
  "Government of Bangladesh": "গণপ্রজাতন্ত্রী বাংলাদেশ সরকার",
  "Government of the People": "গণপ্রজাতন্ত্রী বাংলাদেশ সরকার",
  "GOVERNMENT OF THE PEOPLE'S REPUBLIC OF BANGLADESH": "গণপ্রজাতন্ত্রী বাংলাদেশ সরকার",
  "Government of the People's Republic of Bangladesh": "গণপ্রজাতন্ত্রী বাংলাদেশ সরকার",
  "Guardian Information": "অভিভাবকের তথ্য",
  "Guardian NID": "অভিভাবকের এনআইডি",
  "Has another card": "অন্য কার্ড আছে",
  "Has another card?": "অন্য কার্ড আছে?",
  "Health & Sanitation": "স্বাস্থ্য ও স্যানিটেশন",
  "Health Center Information": "স্বাস্থ্য কেন্দ্রের তথ্য",
  "Health Info": "স্বাস্থ্য তথ্য",
  "Health Notices": "স্বাস্থ্য বিজ্ঞপ্তি",
  "Health Officer": "স্বাস্থ্য কর্মকর্তা",
  "High": "উচ্চ",
  "Hinduism": "হিন্দু",
  "History": "ইতিহাস",
  "Hold the Farmer Card QR code in front of the camera": "কৃষক কার্ডের কিউআর কোড ক্যামেরার সামনে ধরুন",
  "Hold the LPG card QR code in front of the camera": "এলপিজি কার্ডের কিউআর কোড ক্যামেরার সামনে ধরুন",
  "Hold the VGD/VGF card QR code in front of the camera": "VGD/VGF কার্ডের কিউআর কোড ধরুন",
  "Holding Location Map": "হোল্ডিং অবস্থান মানচিত্র",
  "Holding Number": "হোল্ডিং নম্বর",
  "Holding Tax": "হোল্ডিং ট্যাক্স",
  "Holding Tax New Registration Form": "হোল্ডিং ট্যাক্স নিবন্ধন আবেদন ফরম",
  "Holding Tax Ownership Transfer Application Form": "হোল্ডিং মালিকানা হস্তান্তর আবেদন ফরম",
  "Holdings Map": "হোল্ডিং মানচিত্র",
  "House no., road, area...": "বাড়ি নম্বর, রাস্তা, এলাকা...",
  "Household Waste": "গৃহস্থালি বর্জ্য",
  "Husband": "স্বামী",
  "ID": "আইডি",
  "In Progress": "চলমান",
  "Inactive": "নিষ্ক্রিয়",
  "Income": "আয়",
  "Infrastructure": "অবকাঠামো",
  "Infrastructure Application Management": "অবকাঠামো আবেদন ব্যবস্থাপনা",
  "Infrastructure Map": "অবকাঠামো মানচিত্র",
  "Infrastructure Status": "অবকাঠামোর অবস্থা",
  "Invalid or expired OTP ❌": "ভুল বা মেয়াদোত্তীর্ণ OTP ❌",
  "Islam": "ইসলাম",
  "Issue Type": "সমস্যার ধরন",
  "JPG, PNG or PDF · Max 5MB": "JPG, PNG বা PDF · সর্বোচ্চ ৫MB",
  "Land (acres)": "জমি (একর)",
  "Land Information": "জমির তথ্য",
  "Last Collection": "শেষ সংগ্রহ",
  "License Number": "লাইসেন্স নম্বর",
  "License Renewal": "লাইসেন্স নবায়ন",
  "Link Invalid or Expired": "লিংক অকার্যকর বা মেয়াদোত্তীর্ণ",
  "List of vendors barred from bidding in E-Tender": "ই-টেন্ডারে বিড করা থেকে বাধাপ্রাপ্ত বিক্রেতার তালিকা",
  "Live Municipality GIS Map": "লাইভ পৌরসভা জিআইএস মানচিত্র",
  "Loading your applications...": "লোড হচ্ছে...",
  "Loading...": "লোড হচ্ছে...",
  "Location": "অবস্থান",
  "Login": "লগইন",
  "Logout": "লগআউট",
  "Lot No.": "লট নং",
  "Low": "নিম্ন",
  "Low Stock": "কম মজুদ",
  "LPG Card": "এলপিজি কার্ড",
  "LPG Card Admin": "এলপিজি কার্ড অ্যাডমিন",
  "LPG Card Application Form — Ministry of Energy & Mineral Resources": "এলপিজি কার্ড আবেদন ফরম",
  "LPG Card Apply": "এলপিজি কার্ড আবেদন",
  "LPG Card Status": "এলপিজি কার্ডের অবস্থা",
  "LPG Cylinder Distribution": "এলপিজি সিলিন্ডার বিতরণ",
  "LPG Scan": "এলপিজি স্ক্যান",
  "Madaripur Municipality": "মাদারীপুর পৌরসভা",
  "Madaripur Municipality — E-Governance Management System": "মাদারীপুর পৌরসভা — ই-গভর্ন্যান্স",
  "Maintenance": "রক্ষণাবেক্ষণ",
  "Male": "পুরুষ",
  "Manage": "ব্যবস্থাপনা",
  "Management": "ব্যবস্থাপনা",
  "Manual Entry": "ম্যানুয়াল এন্ট্রি",
  "Maps": "মানচিত্র",
  "Marital Status": "বৈবাহিক অবস্থা",
  "Married": "বিবাহিত",
  "Medical / Funeral Certificate": "চিকিৎসা / দাফন সনদ",
  "Medical Waste": "চিকিৎসা বর্জ্য",
  "Medium": "মাধ্যম",
  "Message": "বার্তা",
  "Meter Number": "মিটার নম্বর",
  "Mobile": "মোবাইল",
  "Mobile Number": "মোবাইল নম্বর",
  "Mobile Number (11 digits)": "মোবাইল নম্বর (১১ ডিজিট)",
  "Mobile number is required": "মোবাইল নম্বর আবশ্যক",
  "Module": "মডিউল",
  "Month": "মাস",
  "Month (YYYY-MM)": "মাস (YYYY-MM)",
  "Monthly Income": "মাসিক আয়",
  "Mother": "মাতা",
  "Mother's Date of Birth": "মাতার জন্ম তারিখ",
  "Mother's Email": "মাতার ইমেইল",
  "Mother's Full Name": "মাতার পূর্ণ নাম",
  "Mother's full name": "মাতার পূর্ণ নাম",
  "Mother's Information": "মাতার তথ্য",
  "Mother's Mobile": "মাতার মোবাইল",
  "Mother's Name": "মাতার নাম",
  "Mother's NID File": "মাতার এনআইডি ফাইল",
  "Mother's NID Number": "মাতার এনআইডি নম্বর",
  "Municipal Authority · Citizen Certificate Application Form": "নাগরিক সনদপত্র আবেদন ফরম",
  "Municipal Authority · Family Certificate Application Form": "পারিবারিক সনদপত্র আবেদন ফরম",
  "Municipal Online Payment Portal — Secure &amp; Official": "অনলাইন পেমেন্ট পোর্টাল",
  "Municipality": "পৌরসভা",
  "My Applications": "আমার আবেদনসমূহ",
  "My Ownership Transfer Applications": "মালিকানা হস্তান্তর আবেদন তালিকা",
  "Nagad": "নগদ",
  "Name": "নাম",
  "Name is required": "নাম আবশ্যক",
  "Nation over everything.": "সবকিছুর উপরে দেশ।",
  "National ID Number": "জাতীয় পরিচয়পত্র নম্বর",
  "Nationality": "জাতীয়তা",
  "New": "নতুন",
  "New Owner": "নতুন মালিক",
  "New Password": "নতুন পাসওয়ার্ড",
  "New Registration": "নতুন নিবন্ধন",
  "New Search": "নতুন সার্চ",
  "Next": "পরবর্তী",
  "NID": "এনআইডি",
  "NID Copy": "এনআইডি কপি",
  "NID Number": "এনআইডি নম্বর",
  "NID number": "এনআইডি নম্বর",
  "NID Scan/Image": "এনআইডি স্ক্যান/ছবি",
  "No": "না",
  "No application found": "কোনো আবেদন পাওয়া যায়নি",
  "No applications found": "কোনো আবেদন পাওয়া যায়নি",
  "No applications found for this number": "কোনো আবেদন পাওয়া যায়নি",
  "No batch found.": "কোনো ব্যাচ পাওয়া যায়নি।",
  "No bins found": "কোনো বিন পাওয়া যায়নি",
  "No complaint found for this number": "এই নম্বরে কোনো অভিযোগ পাওয়া যায়নি",
  "No complaints found": "কোনো অভিযোগ পাওয়া যায়নি",
  "No data found": "কোনো তথ্য পাওয়া যায়নি",
  "No distribution records for this card.": "এই কার্ডের কোনো বিতরণ রেকর্ড নেই।",
  "No distribution records for this cycle.": "এই চক্রে কোনো বিতরণ রেকর্ড নেই।",
  "No distribution records yet.": "এখনো কোনো বিতরণ রেকর্ড নেই।",
  "No email provided — you will not receive notifications. Go back and add an email.": "ইমেইল দেননি — বিজ্ঞপ্তি পাবেন না। আগের ধাপে ফিরে ইমেইল যোগ করুন।",
  "No Income": "আয় নেই",
  "No notices found": "কোনো নোটিশ পাওয়া যায়নি",
  "No notifications available": "কোনো বিজ্ঞপ্তি নেই",
  "No notifications found": "কোনো নোটিফিকেশন পাওয়া যায়নি",
  "No projects found.": "কোনো প্রকল্প পাওয়া যায়নি।",
  "No records found": "কোনো রেকর্ড পাওয়া যায়নি",
  "No requests found": "কোনো অনুরোধ পাওয়া যায়নি",
  "No schedules found": "কোনো সময়সূচি পাওয়া যায়নি",
  "No sessions found.": "কোনো সেশন পাওয়া যায়নি।",
  "No stock entry for this cycle.": "এই চক্রের জন্য কোনো স্টক এন্ট্রি নেই।",
  "No stock found.": "কোনো স্টক পাওয়া যায়নি।",
  "Nothing found for this search": "এই অনুসন্ধানে কিছু পাওয়া যায়নি",
  "Notice Admin": "নোটিশ অ্যাডমিন",
  "Notice Board": "নোটিশ বোর্ড",
  "Notices": "নোটিশ",
  "Notification": "বিজ্ঞপ্তি",
  "Notification Log": "বিজ্ঞপ্তি লগ",
  "Notification Log — Communication Division": "নোটিফিকেশন লগ",
  "Notification Title": "বিজ্ঞপ্তির শিরোনাম",
  "Notifications": "বিজ্ঞপ্তি",
  "Number of Floors": "তলার সংখ্যা",
  "Occupation": "পেশা",
  "Officer / Dealer": "অফিসার / ডিলার",
  "Officer / Dealer Name": "অফিসার / ডিলারের নাম",
  "Official Payment Receipt": "পেমেন্ট রশিদ",
  "Online Payment": "অনলাইন পেমেন্ট",
  "Open": "খোলা",
  "Open Tenders": "খোলা টেন্ডার",
  "Optional": "ঐচ্ছিক",
  "Organic Waste": "জৈব বর্জ্য",
  "Other": "অন্যান্য",
  "Other Card": "অন্য কার্ড",
  "OTP could not be sent": "OTP পাঠানো যায়নি",
  "OTP sent to": "আপনার মোবাইলে OTP পাঠানো হয়েছে",
  "OTP sent to ": "আপনার মোবাইলে OTP পাঠানো হয়েছে",
  "Overdue": "বকেয়া",
  "Overview Dashboard": "সামগ্রিক ড্যাশবোর্ড",
  "Owner Name": "মালিকের নাম",
  "Ownership Transfer": "মালিকানা হস্তান্তর",
  "Paid": "পরিশোধিত",
  "Party": "দল",
  "Passport": "পাসপোর্ট",
  "Passport Admin": "পাসপোর্ট অ্যাডমিন",
  "Passport Type": "পাসপোর্টের ধরন",
  "Password": "পাসওয়ার্ড",
  "Pay Now": "এখন পেমেন্ট করুন",
  "Payment": "পেমেন্ট",
  "Payment Admin": "পেমেন্ট অ্যাডমিন",
  "Payment Amount": "পেমেন্টের পরিমাণ",
  "Payment Date": "পেমেন্টের তারিখ",
  "Payment Details": "পেমেন্টের বিবরণ",
  "Payment Gateway": "পেমেন্ট গেটওয়ে",
  "Payment History": "পেমেন্ট ইতিহাস",
  "Payment Method": "পেমেন্ট পদ্ধতি",
  "Pending": "অপেক্ষমাণ",
  "Permanent Address": "স্থায়ী ঠিকানা",
  "Personal Information": "ব্যক্তিগত তথ্য",
  "Pesticide": "কীটনাশক",
  "Pesticide (L)": "কীটনাশক (লিটার)",
  "Pesticide Stock (Liters)": "কীটনাশক মজুদ (লিটার)",
  "Phone": "ফোন",
  "Pickup Request": "পিকআপ অনুরোধ",
  "Place of Birth": "জন্মস্থান",
  "Place of Death": "মৃত্যুস্থান",
  "Please make sure you used the same number during application": "নিশ্চিত করুন আপনার মোবাইল নম্বর সঠিক",
  "Population": "জনসংখ্যা",
  "Powered by Digital Bangladesh Initiative": "ডিজিটাল বাংলাদেশ উদ্যোগ দ্বারা পরিচালিত",
  "Present Address": "বর্তমান ঠিকানা",
  "Previous": "পূর্ববর্তী",
  "Previous Holding Number": "পূর্বের হোল্ডিং নম্বর",
  "Previous Passport": "পূর্ববর্তী পাসপোর্ট",
  "Print": "প্রিন্ট",
  "Priority": "অগ্রাধিকার",
  "Problem Type": "সমস্যার ধরন",
  "Processing": "প্রক্রিয়াধীন",
  "Profile": "প্রোফাইল",
  "Progress": "অগ্রগতি",
  "Project": "প্রকল্প",
  "Project Budget": "প্রকল্প বাজেট",
  "Project Budget Management — Municipal Finance Division": "প্রকল্প বাজেট ব্যবস্থাপনা",
  "Project List": "প্রকল্প তালিকা",
  "Project Name": "প্রকল্পের নাম",
  "Project Officer": "প্রকল্প কর্মকর্তা",
  "Property Address": "সম্পত্তির ঠিকানা",
  "Property Type": "সম্পত্তির ধরন",
  "Provide agricultural land and subsidy receiving information": "কৃষি জমি এবং ভর্তুকি গ্রহণের তথ্য প্রদান করুন",
  "Provide complete personal information of the card holder": "কার্ডধারীর সম্পূর্ণ ব্যক্তিগত তথ্য প্রদান করুন",
  "Provide complete personal information of the farmer": "কৃষকের সম্পূর্ণ ব্যক্তিগত তথ্য প্রদান করুন",
  "Provide ward, district and nearest dealer information": "ওয়ার্ড, জেলা এবং নিকটস্থ ডিলারের তথ্য দিন",
  "Provide ward, union and family information": "ওয়ার্ড, ইউনিয়ন এবং পরিবারের তথ্য প্রদান করুন",
  "Provide your personal information": "আপনার ব্যক্তিগত তথ্য প্রদান করুন",
  "Public Health Notices — Health &amp; Sanitation Division": "জনস্বাস্থ্য বিজ্ঞপ্তি ব্যবস্থাপনা",
  "Public Notice": "পাবলিক নোটিশ",
  "Publish Date": "প্রকাশের তারিখ",
  "Published": "প্রকাশিত",
  "QR Scan": "কিউআর স্ক্যান",
  "Quantity": "পরিমাণ",
  "Quick Access": "দ্রুত প্রবেশ",
  "Rating": "রেটিং",
  "Reason": "কারণ",
  "Receipt": "রসিদ",
  "Recent Applications": "সাম্প্রতিক আবেদন",
  "Recyclable Waste": "পুনর্ব্যবহারযোগ্য",
  "Refresh": "রিফ্রেশ",
  "Reject": "প্রত্যাখ্যান",
  "Rejected": "প্রত্যাখ্যাত",
  "Rejection Reason": "প্রত্যাখ্যানের কারণ",
  "Relationship to Deceased": "মৃত ব্যক্তির সাথে সম্পর্ক",
  "Religion": "ধর্ম",
  "Remaining": "অবশিষ্ট",
  "Remaining (kg)": "অবশিষ্ট (কেজি)",
  "Remaining (৳)": "অবশিষ্ট (৳)",
  "Remaining Stock": "অবশিষ্ট স্টক",
  "Remarks": "মন্তব্য",
  "Renewal": "নবায়ন",
  "Reply": "উত্তর",
  "Reports": "প্রতিবেদন",
  "Request List": "অনুরোধ তালিকা",
  "Request New Link": "নতুন লিংক অনুরোধ",
  "Request special waste collection": "বিশেষ বর্জ্য সংগ্রহের জন্য অনুরোধ জানান",
  "Required": "আবশ্যক",
  "Required Documents Upload": "প্রয়োজনীয় কাগজপত্র আপলোড",
  "Reset": "রিসেট",
  "Reset Form": "ফর্ম রিসেট",
  "Resolution": "নিষ্পত্তি",
  "Resolved": "সমাধান হয়েছে",
  "Retry": "পুনরায় চেষ্টা",
  "Review and approve farmer card applications": "কৃষক কার্ডের আবেদন পর্যালোচনা ও অনুমোদন করুন",
  "Review and approve LPG card applications": "এলপিজি কার্ডের আবেদন পর্যালোচনা ও অনুমোদন করুন",
  "Review and manage all infrastructure requests": "সকল আবেদন পর্যালোচনা ও অনুমোদন করুন",
  "Rice": "চাল",
  "Rice (KG)": "চাল (কেজি)",
  "Rice (kg)": "চাল (কেজি)",
  "Road": "রাস্তা",
  "Road Infrastructure Development Request Form": "রাস্তা অবকাঠামো উন্নয়ন আবেদন ফর্ম",
  "Road Maintenance": "রাস্তা রক্ষণাবেক্ষণ",
  "Road Name": "রাস্তার নাম",
  "Rocket": "রকেট",
  "Role": "ভূমিকা",
  "Roles & Permissions": "ভূমিকা ও অনুমতি",
  "Salary Management": "বেতন ব্যবস্থাপনা",
  "Sanitation Monitoring &amp; Complaint — Health &amp; Sanitation Division": "পয়ঃনিষ্কাশন পর্যবেক্ষণ ও অভিযোগ",
  "Save": "সংরক্ষণ করুন",
  "Scan": "স্ক্যান",
  "Scan a card or enter the number": "কার্ড স্ক্যান করুন বা নম্বর লিখুন",
  "Scan QR Code": "কিউআর কোড স্ক্যান করুন",
  "Schedule Information": "সময়সূচির তথ্য",
  "Schedule List": "সময়সূচি তালিকা",
  "Search": "খুঁজুন",
  "Search by area / ward / type...": "এলাকা / ওয়ার্ড / ধরন দিয়ে খুঁজুন...",
  "Search by name or NID...": "নাম বা NID দিয়ে খুঁজুন...",
  "Search by name...": "নাম দিয়ে খুঁজুন...",
  "Search...": "খুঁজুন...",
  "Searching...": "খোঁজা হচ্ছে...",
  "see all →": "সব দেখুন →",
  "Select": "নির্বাচন করুন",
  "Select Ward": "ওয়ার্ড নির্বাচন করুন",
  "Send approval and vaccination schedule to this email": "অনুমোদন ও টিকার সময়সূচি এই ইমেইলে পাঠানো হবে",
  "Send Email": "ইমেইল পাঠান",
  "Send Notification": "বিজ্ঞপ্তি পাঠান",
  "Send Notification — Communication Division": "নোটিফিকেশন পাঠান",
  "Send OTP": "OTP পাঠান",
  "Send Push Notification": "পুশ বিজ্ঞপ্তি পাঠান",
  "Send Reply": "উত্তর পাঠান",
  "Send SMS": "এসএমএস পাঠান",
  "Service Report": "সেবা প্রতিবেদন",
  "Service Type": "সেবার ধরন",
  "Services": "সেবাসমূহ",
  "Session": "সেশন",
  "Session Code": "সেশন কোড",
  "Set New Password": "নতুন পাসওয়ার্ড সেট করুন",
  "Settings": "সেটিংস",
  "Sewage Monitoring": "পয়ঃনিষ্কাশন পর্যবেক্ষণ",
  "Sign In": "সাইন ইন",
  "Sister": "বোন",
  "Smart Bin List": "স্মার্ট বিন তালিকা",
  "Smart Bin Monitor": "স্মার্ট বিন মনিটর",
  "Smart Bin Monitoring": "স্মার্ট বিন পর্যবেক্ষণ",
  "Social Cards": "সামাজিক কার্ড",
  "Social Cards Analytics": "সামাজিক কার্ড বিশ্লেষণ",
  "Socio-economic Information": "আর্থ-সামাজিক তথ্য",
  "Son": "পুত্র",
  "Start": "শুরু",
  "Start Camera": "ক্যামেরা চালু",
  "Start Date": "শুরুর তারিখ",
  "Start Scan": "স্ক্যান শুরু",
  "Status": "স্ট্যাটাস",
  "Status Check": "অবস্থা যাচাই",
  "Stock": "স্টক",
  "Stock & Distribution": "স্টক ও বিতরণ",
  "Stop Scan": "স্ক্যান বন্ধ",
  "Street Light": "সড়কবাতি",
  "Subject": "বিষয়",
  "Submission Deadline": "জমার শেষ তারিখ",
  "Submit": "জমা দিন",
  "Submit Another Bid": "আরেকটি বিড জমা দিন",
  "Submit Application": "আবেদন জমা দিন",
  "Submit Application →": "আবেদন জমা দিন →",
  "Submit Bid": "বিড জমা দিন",
  "Submit Complaint": "অভিযোগ দাখিল",
  "Submit Pickup Request": "পিকআপ অনুরোধ দাখিল করুন",
  "Submitting...": "জমা হচ্ছে...",
  "Success": "সফল",
  "Successfully changed password. Please log in with your new password.": "আপনার পাসওয়ার্ড সফলভাবে পরিবর্তন হয়েছে। এখন নতুন পাসওয়ার্ড দিয়ে লগইন করুন।",
  "Super Admin": "সুপার অ্যাডমিন",
  "Suspend": "স্থগিত করুন",
  "Suspended": "স্থগিত",
  "Symbol": "প্রতীক",
  "System": "সিস্টেম",
  "System Online": "সিস্টেম সক্রিয়",
  "System Settings": "সিস্টেম সেটিংস",
  "Task Assignment": "কাজ বরাদ্দ",
  "Tax Applications": "কর আবেদন",
  "Tax Assessment": "কর নির্ধারণ",
  "Tax Due List": "বকেয়া কর তালিকা",
  "Tax Payment": "কর পরিশোধ",
  "TCB Distribution": "টিসিবি বিতরণ",
  "TCB Stock": "টিসিবি স্টক",
  "Tender Notices": "টেন্ডার বিজ্ঞপ্তি",
  "Tender Title": "টেন্ডারের শিরোনাম",
  "This category has no notices.": "এই ক্যাটাগরিতে কোনো নোটিশ নেই।",
  "This month distribution record": "এই মাসের বিতরণ রেকর্ড করুন",
  "Time": "সময়",
  "Toggle": "টগল",
  "Total": "মোট",
  "Total Applications": "মোট আবেদন",
  "Total Bids": "মোট বিড",
  "Total Bins": "মোট বিন",
  "Total Cards": "মোট কার্ড",
  "Total Citizens": "মোট নাগরিক",
  "Total Distributed": "মোট বিতরণ",
  "Total Projects": "মোট প্রকল্প",
  "Total Published": "মোট প্রকাশিত",
  "Total Records": "মোট রেকর্ড",
  "Total Stock": "মোট স্টক",
  "Total Tenders": "মোট টেন্ডার",
  "Tracking": "ট্র্যাকিং",
  "Trade License": "ট্রেড লাইসেন্স",
  "Trade License Application Form": "ট্রেড লাইসেন্স আবেদন ফরম",
  "Trade License Renewal Form": "ট্রেড লাইসেন্স নবায়ন ফরম",
  "Transaction ID": "লেনদেন আইডি",
  "Two-step approval is not complete yet. The PDF will be available after final approval.": "দুই ধাপের অনুমোদন এখনো সম্পূর্ণ হয়নি। চূড়ান্ত অনুমোদনের পরে PDF ডাউনলোড করা যাবে।",
  "Type": "ধরন",
  "Type the number exactly as shown on the card": "কার্ডের উপরের নম্বরটি হুবহু টাইপ করুন",
  "Under Review": "পর্যালোচনাধীন",
  "Union": "ইউনিয়ন",
  "Union Parishad / Municipality — Citizen Service Portal": "ইউনিয়ন পরিষদ / পৌরসভা — নাগরিক সেবা পোর্টাল",
  "Unit": "একক",
  "Units Consumed": "ব্যবহৃত ইউনিট",
  "Unmarried": "অবিবাহিত",
  "Unpaid": "অপরিশোধিত",
  "Upazila": "উপজেলা",
  "Upcoming Election": "আসন্ন নির্বাচন",
  "Update": "হালনাগাদ",
  "Upload Father": "পিতার এনআইডি আপলোড",
  "Upload Father's NID": "পিতার এনআইডি আপলোড",
  "Upload Mother": "মাতার এনআইডি আপলোড",
  "Upload Mother's NID": "মাতার এনআইডি আপলোড",
  "Upload NID Card": "এনআইডি কার্ড আপলোড",
  "Upload Vaccine / EPI Card": "টিকা / ইপিআই কার্ড আপলোড",
  "Use the code below for this demo verification.": "ডেমো মোডে নিচের কোডটি ব্যবহার করুন।",
  "Use the services below or check the Notice Board.": "নিচের সেবাগুলি ব্যবহার করুন বা নোটিশ বোর্ড দেখুন।",
  "User Approval": "ব্যবহারকারী অনুমোদন",
  "User Roles": "ব্যবহারকারীর ভূমিকা",
  "Username": "ব্যবহারকারীর নাম",
  "Vaccine Card (EPI Card)": "টিকা কার্ড (ইপিআই কার্ড)",
  "Validating reset link…": "রিসেট লিংক যাচাই হচ্ছে…",
  "Vendor Blacklist": "ব্ল্যাকলিস্টেড বিক্রেতা",
  "Vendor Name": "বিক্রেতার নাম",
  "Verify": "যাচাই করুন",
  "Verify OTP": "OTP যাচাই করুন",
  "Verifying information...": "তথ্য যাচাই হচ্ছে...",
  "VGD / VGF Card": "ভিজিডি / ভিজিএফ কার্ড",
  "VGD Card Admin": "ভিজিডি কার্ড অ্যাডমিন",
  "VGD Card Apply": "ভিজিডি কার্ড আবেদন",
  "VGD Card Status": "ভিজিডি কার্ডের অবস্থা",
  "VGD Distribution": "ভিজিডি বিতরণ",
  "VGD History": "ভিজিডি ইতিহাস",
  "VGD Stock": "ভিজিডি স্টক",
  "VGD/VGF Distribution History": "VGD/VGF বিতরণ ইতিহাস",
  "VGD/VGF Distribution Session": "VGD/VGF বিতরণ সেশন",
  "VGD/VGF Stock Management": "VGD/VGF স্টক ব্যবস্থাপনা",
  "View": "দেখুন",
  "View Details": "বিস্তারিত",
  "View history by card number": "কার্ড নম্বর দিয়ে ইতিহাস দেখুন",
  "View NID File": "এনআইডি ফাইল দেখুন",
  "View the list of government tenders and submit bids online.": "সরকারি টেন্ডারের তালিকা দেখুন এবং অনলাইনে বিড জমা দিন।",
  "Voter Approval": "ভোটার অনুমোদন",
  "Voter Registration": "ভোটার নিবন্ধন",
  "Voter Registration Form — E-Voting System": "ভোটার নিবন্ধন ফরম",
  "Vulnerable Group Development / Feeding Card Application — Ministry of Women & Children Affairs": "VGD / VGF কার্ড আবেদন ফরম",
  "Waiting": "অপেক্ষমান",
  "Ward": "ওয়ার্ড",
  "Ward Based": "ওয়ার্ড ভিত্তিক",
  "Ward is required": "ওয়ার্ড আবশ্যক",
  "Ward List": "ওয়ার্ড তালিকা",
  "Ward Map": "ওয়ার্ড মানচিত্র",
  "Ward No": "ওয়ার্ড নং",
  "Ward No.": "ওয়ার্ড নং",
  "Ward Number": "ওয়ার্ড নম্বর",
  "Waste Collection Report": "বর্জ্য সংগ্রহ প্রতিবেদন",
  "Waste Management": "বর্জ্য ব্যবস্থাপনা",
  "Waste Mgmt.": "বর্জ্য ব্যবস্থাপনা",
  "Waste Pickup Request": "বর্জ্য পিকআপ অনুরোধ",
  "Waste Type": "বর্জ্যের ধরন",
  "Water Bill": "পানির বিল",
  "Water Bill Generation Form": "পানি বিল তৈরি ফরম",
  "Water Bill Generation System — Municipality Water Supply": "পানি বিল তৈরি ফরম",
  "Water Connection": "পানি সংযোগ",
  "Water Connection Application Form": "পানি সংযোগ আবেদন ফরম",
  "Water Supply": "পানি সরবরাহ",
  "Water Supply Connection Application Form": "পানি সংযোগ আবেদন ফরম",
  "Water Supply Rate Chart": "পানি সরবরাহ শুল্ক তালিকা",
  "Water Usage Report": "পানি ব্যবহার প্রতিবেদন",
  "Welcome!": "স্বাগতম!",
  "What action do you want to take on the card?": "কার্ডে কোন অ্যাকশন নিতে চান?",
  "Wheat": "গম",
  "Wheat (KG)": "গম (কেজি)",
  "Wheat (kg)": "গম (কেজি)",
  "Widowed": "বিধবা/বিধুর",
  "Wife": "স্ত্রী",
  "Write reason...": "কারণ লিখুন...",
  "Yes": "হ্যাঁ",
  "You do not have permission to view this page with your current role.": "আপনার বর্তমান ভূমিকা দিয়ে এই পেজটি দেখার অনুমতি নেই।",
  "Your Applications": "আপনার আবেদনসমূহ",
  "Your feedback has been received. Our team will review it shortly.": "আপনার ফিডব্যাক গ্রহণ করা হয়েছে। আমাদের দল শীঘ্রই পর্যালোচনা করবে।",
  "Your full name": "আপনার সম্পূর্ণ নাম",
  "Your OTP Code": "আপনার OTP কোড",
  "Your payment has been completed and a receipt has been generated.": "আপনার পেমেন্ট সম্পন্ন হয়েছে এবং রশিদ তৈরি হয়েছে।",
  "© 2025 Municipal E-Governance. All rights reserved.": "© ২০২৫ মিউনিসিপ্যাল ই-গভর্ন্যান্স। সর্বস্বত্ব সংরক্ষিত।",
  "— Select —": "— নির্বাচন করুন —",
  "✓ Application submitted successfully": "✓ আবেদন সফলভাবে জমা হয়েছে",
};
